# Generated by Django 5.2 on 2026-02-18 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity_in_stock', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, help_text='Enter the year of publication', null=True, verbose_name='publication year')),
                ('cover_image_url', models.ImageField(upload_to='books/')),
                ('catalog_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.catalog')),
            ],
        ),
    ]
