# Generated by Django 5.2 on 2026-02-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
