# Generated by Django 5.2 on 2026-03-01 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название издательства')),
                ('publisher_brand', models.CharField(blank=True, help_text='Например: "Эксмо", "АСТ" и т.д.', max_length=200, verbose_name='Издательский бренд')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AddField(
            model_name='book',
            name='age_restriction',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)], verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hard', 'Твёрдая обложка'), ('soft', 'Мягкая обложка'), ('special', 'Специальная обложка')], default='hard', max_length=10, verbose_name='Тип обложки'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher_brand',
            field=models.CharField(blank=True, help_text='Может отличаться от названия издательства', max_length=200, verbose_name='Издательский бренд'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher', verbose_name='Издательство'),
        ),
    ]
