# Generated by Django 5.2 on 2026-03-01 13:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_publisher_alter_book_options_book_age_restriction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restriction',
            field=models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (16, '16+'), (18, '18+')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_type',
            field=models.CharField(choices=[('hard', 'Твёрдая обложка'), ('soft', 'Мягкая обложка'), ('special', 'Специальная обложка')], default='hard', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher_brand',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
