# Generated by Django 5.2 on 2026-03-01 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_options_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Publisher'},
        ),
    ]
