# Generated by Django 5.2 on 2026-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher_brand',
            field=models.CharField(max_length=200),
        ),
    ]
